return {
	{
		name = "Stone",
		properties = {},
		rarity = 2,
	},
	{
		name = "Copper",
		properties = {
			Color = Color3.fromRGB(160, 95, 53),
			Material = Enum.Material.Foil,
		},
		rarity = 40,
	},
	{
		name = "Iron",
		properties = {
			Color = Color3.fromRGB(199, 176, 119),
			Material = Enum.Material.Slate,
		},
		rarity = 55,
	},
	{
		name = "Quartz",
		properties = {
			Color = Color3.fromRGB(202, 203, 209),
			Material = Enum.Material.SmoothPlastic,
			Transparency = 0.05,
			Reflectance = 0.25,
		},
		rarity = 50,
	},
	{
		name = "Agate",
		properties = {
			Color = Color3.fromRGB(199, 119, 199),
			Material = Enum.Material.Glacier,
		},
		rarity = 285,
	},
	{
		name = "Coal",
		properties = {
			Color = Color3.fromRGB(27, 42, 53),
			Material = Enum.Material.Pebble,
			Reflectance = 0.2,
		},
		rarity = 25,
	},
	{
		name = "Purple",
		properties = {
			Color = Color3.new(0.5, 0.000000, 1.000000),
			Material = Enum.Material.Neon,
		},
		rarity = 10_000,
	},
}
